# Generated by Django 5.0.1 on 2024-10-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRHH', '0002_initial'),
        ('agro_supplies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsubcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agro_supplies.company', verbose_name='Empresa del Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvariety',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoryequipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro_supplies.categoryequipment', verbose_name='Categoria Padre'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro_supplies.company', verbose_name='Empresa del Proveedor'),
        ),
        migrations.AddField(
            model_name='supply',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='agro_supplies.category'),
        ),
        migrations.AddField(
            model_name='supply',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='agro_supplies.company'),
        ),
        migrations.AddField(
            model_name='supply',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='agro_supplies.subcategory'),
        ),
        migrations.AddField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='agro_supplies.supplier'),
        ),
        migrations.AddField(
            model_name='toolandequipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro_supplies.categoryequipment', verbose_name='Categoria de la herramienta'),
        ),
        migrations.AddField(
            model_name='toolandequipment',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro_supplies.subcategoryequipment', verbose_name='Subcategoria de la herramienta'),
        ),
        migrations.AddField(
            model_name='toolassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RRHH.employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='toolassignment',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='agro_supplies.toolandequipment', verbose_name='Herramienta'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RRHH.employee'),
        ),
        migrations.AddField(
            model_name='toolandequipment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='agro_supplies.warehouse'),
        ),
        migrations.AddField(
            model_name='supply',
            name='warehouse',
            field=models.ManyToManyField(to='agro_supplies.warehouse'),
        ),
    ]
