# Generated by Django 4.2.2 on 2023-09-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agro_supplies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvariety",
            name="documentation_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="documentation_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="environmental_requirements",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="general_recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="harvest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="health",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="herbicide_susceptibility",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="ica_producer_record",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="nutrition",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="overturning",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="record_holder",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="siembra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="tillering",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvariety",
            name="vigor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="documentation_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="documentation_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="environmental_requirements",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="general_recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="harvest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="health",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="herbicide_susceptibility",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="ica_producer_record",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="nutrition",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="overturning",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="record_holder",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="siembra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="tillering",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="variety",
            name="vigor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
