# Generated by Django 4.2.2 on 2023-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RRHH", "0003_alter_contractoremployee_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractoremployee",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Pon apuntes consideres necesarios ",
                max_length=100,
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractoremployee",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Pon apuntes consideres necesarios ",
                max_length=100,
                null=True,
                verbose_name="Descripción",
            ),
        ),
    ]
