# Generated by Django 5.0.1 on 2024-10-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRHH', '0002_initial'),
        ('agro_supplies', '0002_initial'),
        ('crop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalagriculturalapplication',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalagriculturalapplication',
            name='insumo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agro_supplies.supply', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='historicalagriculturework',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalagriculturework',
            name='insumos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agro_supplies.supply'),
        ),
        migrations.AddField(
            model_name='historicalagriculturework',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='RRHH.employee', verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='historicalagriculturework',
            name='tool_and_equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agro_supplies.toolandequipment', verbose_name='Herramientas y Equipos'),
        ),
        migrations.AddField(
            model_name='historicalagriculturework',
            name='work_crop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crop.crop', verbose_name='Cultivo'),
        ),
        migrations.AddField(
            model_name='historicalcrop',
            name='agriculture_work',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crop.agriculturework', verbose_name='crops'),
        ),
        migrations.AddField(
            model_name='historicalcrop',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcrop',
            name='variety',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agro_supplies.variety', verbose_name='Variedad'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='crop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crop.crop', verbose_name='Cultivo'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstatelot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='agriculture_work',
            field=models.ManyToManyField(blank=True, related_name='agricultural_works', to='crop.agriculturework', verbose_name='lots'),
        ),
        migrations.AddField(
            model_name='lot',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.crop', verbose_name='Cultivo'),
        ),
        migrations.AddField(
            model_name='lot',
            name='manager',
            field=models.ManyToManyField(blank=True, to='RRHH.employee', verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='historicalagriculturework',
            name='work_lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crop.lot', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='agriculturework',
            name='work_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.lot', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='lot',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.statelot', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crop.statelot', verbose_name='Estado'),
        ),
    ]
